import '../public/report-formats-core.js';
const C=globalThis.PMIX_FORMAT_CORE;
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
export default async function formatsApi(request,env,owner){
 const url=new URL(request.url);if(url.pathname!=='/api/report-formats')return json({error:'Not found'},404);
 if(request.method==='GET'){const {results}=await env.DB.prepare('SELECT id,data,revision,deleted,updated FROM report_formats WHERE owner=? ORDER BY updated').bind(owner).all();return json({formats:results.map(r=>({id:r.id,format:JSON.parse(r.data),revision:r.revision,deleted:!!r.deleted,updated:r.updated}))});}
 if(!['POST','DELETE'].includes(request.method))return json({error:'Method not allowed'},405);
 const text=await request.text();if(text.length>12000)return json({error:'Format settings are too large.'},413);let b,f;try{b=JSON.parse(text);if(!Number.isSafeInteger(b.revision)||b.revision<0)throw Error('Invalid format revision.');if(request.method==='POST')f=C.validate(b.format);else{if(typeof b.id!=='string'||!/^[-a-z0-9]{3,80}$/i.test(b.id))throw Error('Invalid format ID.');}}catch(e){return json({error:e.message||'Invalid format settings.'},400);}
 const id=f?.id||b.id,old=await env.DB.prepare('SELECT data,revision,deleted FROM report_formats WHERE owner=? AND id=?').bind(owner,id).first();if((old?.revision||0)!==b.revision)return json({error:'This format changed on another device. Close this editor, refresh formats, and reopen it before saving.'},409);
 const deleted=request.method==='DELETE';if(deleted&&!old){const builtin=C.builtins.find(f=>f.id===id);if(!builtin)return json({error:'Format not found.'},404);f=builtin;}
 const data=deleted?old?.data||JSON.stringify(f):JSON.stringify(f);if(old&&old.data===data&&!!old.deleted===deleted)return json({changed:false,revision:old.revision});const count=await env.DB.prepare('SELECT COUNT(*) AS n FROM report_formats WHERE owner=? AND deleted=0').bind(owner).first();if(!deleted&&(!old||old.deleted)&&count.n>=100)return json({error:'You have 100 saved formats. Delete an unused format first.'},400);
 const updated=new Date().toISOString(),revision=(old?.revision||0)+1;const results=await env.DB.batch([env.DB.prepare('INSERT INTO report_formats(owner,id,data,revision,deleted,updated) VALUES(?,?,?,?,?,?) ON CONFLICT(owner,id) DO UPDATE SET data=excluded.data,revision=excluded.revision,deleted=excluded.deleted,updated=excluded.updated WHERE report_formats.revision=?').bind(owner,id,data,revision,deleted?1:0,updated,b.revision),env.DB.prepare('INSERT INTO learning_history(owner,profile,action,updated) SELECT ?,?,?,? WHERE changes()=1').bind(owner,deleted?JSON.parse(data).name:f.name,deleted?'Deleted report format':old?'Updated report format':'Saved report format',updated)]);if((results[0].meta?.changes??results[0].changes)===0)return json({error:'This format changed on another device. Refresh formats before saving.'},409);return json({changed:true,revision,updated});
}
