/** Local source/file tools. Generated programs are downloaded, never executed by this page. */
const encoder=new TextEncoder();
export const escapeXML=s=>String(s).replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\ufffe\uffff]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export function safeName(name){const value=String(name).replace(/\\/g,'/');if(!value||value.length>160||value.startsWith('/')||value.split('/').some(p=>!p||p==='.'||p==='..')||/[:\x00-\x1f]/.test(value))throw new Error('Use a relative filename without parent folders or special control characters.');return value;}
export async function importTextFiles(files){const selected=[...files];if(selected.length>6)throw new Error('Attach up to six files per message.');if(selected.reduce((n,f)=>n+f.size,0)>512000)throw new Error('Keep selected text files below 500 KB in total.');const out=[];for(const file of selected){if(!/\.(txt|md|csv|tsv|json|html?|css|[cm]?js|jsx|tsx?|py|swift|kt|java|c|cpp|h|hpp|rs|go|rb|php|sh|sql|xml|ya?ml|toml|ini)$/i.test(file.name))throw new Error(`${file.name}: use text, source, CSV or JSON. The desktop edition handles PDF/Office attachments.`);const text=await file.text();if(text.includes('\0'))throw new Error('Binary files cannot be read as source text.');out.push({name:safeName(file.name),text:text.slice(0,100000)});}return out;}
let crcTable;function crc32(bytes){if(!crcTable)crcTable=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=(n&1)?0xedb88320^(n>>>1):n>>>1;return n>>>0;});let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
function header(size){const bytes=new Uint8Array(size);return {bytes,view:new DataView(bytes.buffer)};}
export function zip(files){if(!files.length||files.length>100)throw new Error('Choose 1–100 files.');const parts=[],directory=[];let offset=0,total=0;const names=new Set();for(const file of files){const path=safeName(file.name);if(names.has(path))throw new Error('Duplicate filename.');names.add(path);const name=encoder.encode(path),data=typeof file.text==='string'?encoder.encode(file.text):file.bytes;total+=data.length;if(total>8000000)throw new Error('Export is limited to 8 MB.');const crc=crc32(data),local=header(30);local.view.setUint32(0,0x04034b50,true);local.view.setUint16(4,20,true);local.view.setUint16(6,0x0800,true);local.view.setUint32(14,crc,true);local.view.setUint32(18,data.length,true);local.view.setUint32(22,data.length,true);local.view.setUint16(26,name.length,true);parts.push(local.bytes,name,data);const central=header(46);central.view.setUint32(0,0x02014b50,true);central.view.setUint16(4,20,true);central.view.setUint16(6,20,true);central.view.setUint16(8,0x0800,true);central.view.setUint32(16,crc,true);central.view.setUint32(20,data.length,true);central.view.setUint32(24,data.length,true);central.view.setUint16(28,name.length,true);central.view.setUint32(42,offset,true);directory.push(central.bytes,name);offset+=30+name.length+data.length;}const bytes=directory.reduce((n,b)=>n+b.length,0),end=header(22);end.view.setUint32(0,0x06054b50,true);end.view.setUint16(8,files.length,true);end.view.setUint16(10,files.length,true);end.view.setUint32(12,bytes,true);end.view.setUint32(16,offset,true);return new Blob([...parts,...directory,end.bytes],{type:'application/zip'});}
export function download(name,content,type='text/plain;charset=utf-8'){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=safeName(name).split('/').at(-1);a.rel='noopener';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
const declaration='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
const relNS='http://schemas.openxmlformats.org/package/2006/relationships';
const offNS='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
function relationships(rows){return declaration+`<Relationships xmlns="${relNS}">${rows.map(([id,type,target])=>`<Relationship Id="${id}" Type="${offNS}/${type}" Target="${escapeXML(target)}"/>`).join('')}</Relationships>`;}
function types(rows){return declaration+`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${rows.map(([part,type])=>`<Override PartName="${part}" ContentType="application/vnd.openxmlformats-officedocument.${type}+xml"/>`).join('')}</Types>`;}
export function docx(text){if(text.split('\n').length>2000)throw new Error('Word export is limited to 2,000 paragraphs. Split the document before exporting.');const paras=text.split('\n').map(line=>`<w:p><w:r><w:t xml:space="preserve">${escapeXML(line)}</w:t></w:r></w:p>`).join('');return zip([{name:'[Content_Types].xml',text:types([['/word/document.xml','wordprocessingml.document.main']])},{name:'_rels/.rels',text:relationships([['rId1','officeDocument','word/document.xml']])},{name:'word/document.xml',text:declaration+`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paras}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`}]);}
export function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if(c==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;if(rows.length>10000||cell.length>100000)throw new Error('CSV exceeds local processing limits.');}if(quoted)throw new Error('A CSV quoted field is not closed.');if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
export function csvStats(text){const rows=parseCSV(text);if(rows.length<2)return 'The CSV needs a header and at least one data row.';return `Rows: ${rows.length-1}; columns: ${rows[0].length}.\n`+rows[0].map((name,i)=>{const values=rows.slice(1).map(row=>row[i]).filter(x=>x!==undefined&&x.trim()!=='');if(!values.length)return `${name}: empty.`;if(!values.every(v=>/^[-+]?\d*\.?\d+(?:e[-+]?\d+)?$/i.test(v)))return `${name}: ${values.length} nonempty values.`;const numbers=values.map(Number);if(!numbers.every(Number.isFinite))return `${name}: numeric range unsupported.`;const sum=numbers.reduce((a,b)=>a+b,0);if(!Number.isFinite(sum))return `${name}: numeric range unsupported.`;return `${name}: count ${numbers.length}; min ${Math.min(...numbers)}; max ${Math.max(...numbers)}; mean ${sum/numbers.length}; sum ${sum}.`;}).join('\n');}
function column(n){let text='';do{text=String.fromCharCode(65+n%26)+text;n=Math.floor(n/26)-1;}while(n>=0);return text;}
export function xlsx(text){const rows=parseCSV(text);if(rows.length>5000)throw new Error('Excel export is limited to 5,000 rows. Split the table before exporting.');if(rows.some(r=>r.length>100))throw new Error('Limit spreadsheets to 100 columns.');const sheet=declaration+'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map((row,i)=>`<row r="${i+1}">`+row.map((cell,j)=>{const ref=column(j)+(i+1),numeric=/^[-+]?\d*\.?\d+(?:e[-+]?\d+)?$/i.test(cell)&&Number.isFinite(Number(cell));return numeric?`<c r="${ref}"><v>${Number(cell)}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${escapeXML(cell)}</t></is></c>`;}).join('')+'</row>').join('')+'</sheetData></worksheet>';return zip([{name:'[Content_Types].xml',text:types([['/xl/workbook.xml','spreadsheetml.sheet.main'],['/xl/worksheets/sheet1.xml','spreadsheetml.worksheet']])},{name:'_rels/.rels',text:relationships([['rId1','officeDocument','xl/workbook.xml']])},{name:'xl/workbook.xml',text:declaration+`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="${offNS}"><sheets><sheet name="MAX-G" sheetId="1" r:id="rId1"/></sheets></workbook>`},{name:'xl/_rels/workbook.xml.rels',text:relationships([['rId1','worksheet','worksheets/sheet1.xml']])},{name:'xl/worksheets/sheet1.xml',text:sheet}]);}
export function pptx(text) {
  const slides=String(text).split(/\n(?=#{1,2} )/).filter(value=>value.trim());
  if(!slides.length)throw new Error('Write slide content first.');
  if(slides.length>12)throw new Error('Keep presentations to 12 slides or fewer. Split this presentation into smaller files.');
  const prepared=slides.map(slide=>{
    const lines=slide.trim().split('\n').map(line=>line.replace(/^#{1,6}\s*/,''));
    if(lines.length>14||lines.some(line=>Array.from(line).length>180))throw new Error('Keep each slide to 14 lines and each line to 180 characters. Shorten or split the slide; no content was exported.');
    return lines;
  });
  const pNS='http://schemas.openxmlformats.org/presentationml/2006/main';
  const aNS='http://schemas.openxmlformats.org/drawingml/2006/main';
  const ns=`xmlns:a="${aNS}" xmlns:r="${offNS}" xmlns:p="${pNS}"`;
  const group='<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>';
  const scheme=[['dk1','101827'],['lt1','EDF7FF'],['dk2','142238'],['lt2','EAF5FC'],['accent1','7EE7F7'],['accent2','ABA0FF'],['accent3','91E5BD'],['accent4','FFD685'],['accent5','FC9DAC'],['accent6','9BC5FF'],['hlink','7EE7F7'],['folHlink','ABA0FF']];
  const colorScheme=scheme.map(([name,color])=>`<a:${name}><a:srgbClr val="${color}"/></a:${name}>`).join('');
  const font='<a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface=""/>';
  const fills=Array.from({length:3},()=>'<a:solidFill><a:schemeClr val="phClr"/></a:solidFill>').join('');
  const strokes=[9525,19050,28575].map(width=>`<a:ln w="${width}" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/><a:miter lim="800000"/><a:headEnd type="none" w="med" len="med"/><a:tailEnd type="none" w="med" len="med"/></a:ln>`).join('');
  const theme=declaration+`<a:theme xmlns:a="${aNS}" name="MAX-G"><a:themeElements><a:clrScheme name="MAX-G">${colorScheme}</a:clrScheme><a:fontScheme name="MAX-G"><a:majorFont>${font}</a:majorFont><a:minorFont>${font}</a:minorFont></a:fontScheme><a:fmtScheme name="MAX-G"><a:fillStyleLst>${fills}</a:fillStyleLst><a:lnStyleLst>${strokes}</a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst>${fills}</a:bgFillStyleLst></a:fmtScheme></a:themeElements><a:objectDefaults/><a:extraClrSchemeLst/></a:theme>`;
  const master=declaration+`<p:sldMaster ${ns}><p:cSld name="MAX-G"><p:spTree>${group}</p:spTree></p:cSld><p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/><p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rIdLayout"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>`;
  const layout=declaration+`<p:sldLayout ${ns} type="blank" preserve="1"><p:cSld name="Blank"><p:spTree>${group}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`;
  const parts=[
    {name:'[Content_Types].xml',text:types([
      ['/ppt/presentation.xml','presentationml.presentation.main'],
      ['/ppt/slideMasters/slideMaster1.xml','presentationml.slideMaster'],
      ['/ppt/slideLayouts/slideLayout1.xml','presentationml.slideLayout'],
      ['/ppt/theme/theme1.xml','theme'],
      ...slides.map((_,i)=>[`/ppt/slides/slide${i+1}.xml`,'presentationml.slide'])
    ])},
    {name:'_rels/.rels',text:relationships([['rId1','officeDocument','ppt/presentation.xml']])},
    {name:'ppt/presentation.xml',text:declaration+`<p:presentation ${ns}><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rIdMaster"/></p:sldMasterIdLst><p:sldIdLst>${slides.map((_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+1}"/>`).join('')}</p:sldIdLst><p:sldSz cx="12192000" cy="6858000"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`},
    {name:'ppt/_rels/presentation.xml.rels',text:relationships([['rIdMaster','slideMaster','slideMasters/slideMaster1.xml'],...slides.map((_,i)=>[`rId${i+1}`,'slide',`slides/slide${i+1}.xml`])])},
    {name:'ppt/slideMasters/slideMaster1.xml',text:master},
    {name:'ppt/slideMasters/_rels/slideMaster1.xml.rels',text:relationships([['rIdLayout','slideLayout','../slideLayouts/slideLayout1.xml'],['rIdTheme','theme','../theme/theme1.xml']])},
    {name:'ppt/slideLayouts/slideLayout1.xml',text:layout},
    {name:'ppt/slideLayouts/_rels/slideLayout1.xml.rels',text:relationships([['rIdMaster','slideMaster','../slideMasters/slideMaster1.xml']])},
    {name:'ppt/theme/theme1.xml',text:theme}
  ];
  for(const [i,lines]of prepared.entries()) {
    parts.push({name:`ppt/slides/slide${i+1}.xml`,text:declaration+`<p:sld ${ns}><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="101827"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree>${group}<p:sp><p:nvSpPr><p:cNvPr id="2" name="Content"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="640000" y="550000"/><a:ext cx="10912000" cy="5758000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr><p:txBody><a:bodyPr wrap="square"><a:normAutofit/></a:bodyPr><a:lstStyle/>${lines.map((line,j)=>`<a:p><a:r><a:rPr lang="en-US" sz="${j===0?3000:1800}" b="${j===0?1:0}"><a:solidFill><a:srgbClr val="${j===0?'7EE7F7':'EDF7FF'}"/></a:solidFill><a:latin typeface="Arial"/></a:rPr><a:t>${escapeXML(line)}</a:t></a:r></a:p>`).join('')}</p:txBody></p:sp></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`});
    parts.push({name:`ppt/slides/_rels/slide${i+1}.xml.rels`,text:relationships([['rIdLayout','slideLayout','../slideLayouts/slideLayout1.xml']])});
  }
  return zip(parts);
}
export function printReport(text){const win=window.open('','_blank');if(!win)throw new Error('Allow a print window, then try again.');win.opener=null;win.document.open();win.document.write('<!doctype html><html><head><meta charset="utf-8"><title>MAX-G report</title><style>body{font:14px system-ui;margin:2cm;color:#142238}pre{white-space:pre-wrap;font:inherit;line-height:1.6}@media print{body{margin:1cm}}</style></head><body><h1>MAX-G report</h1><pre>'+escapeXML(text)+'</pre></body></html>');win.document.close();win.focus();setTimeout(()=>win.print(),200);}
