/** Bounded public retrieval and deterministic calculation. No eval, model calls, or storage. */
import {symbols,aliases,ambiguous} from './unit-data.js';
export function safePublicURL(raw){try{const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password||u.port)return null;const host=u.hostname.toLowerCase().replace(/\.$/,'');if(!host.includes('.')||host==='localhost'||host.endsWith('.local')||host.endsWith('.internal')||/^[\d.]+$/.test(host)||host.includes(':'))return null;return u.href;}catch{return null;}}
export function proxyBase(raw){const value=String(raw).trim();if(!value)throw new Error('Web search is not connected. Start MAX-G Companion or add an optional Cloudflare Worker URL in Settings → Connection.');const u=new URL(value);const local=['localhost','127.0.0.1'].includes(u.hostname);if((u.protocol!=='https:'&&!(u.protocol==='http:'&&local))||u.username||u.password||u.search||u.hash)throw new Error('Use a plain HTTPS Worker URL, without credentials, query or fragment.');return u.href.replace(/\/$/,'');}
export async function readJSON(url,{signal,timeout=16000,maxBytes=180000}={}){
  const controller=new AbortController();const abort=()=>controller.abort(signal?.reason);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();const timer=setTimeout(()=>controller.abort(new Error('The public service took too long to respond.')),timeout);
  try{const response=await fetch(url,{signal:controller.signal,credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer'});if(Number(response.headers.get('content-length'))>maxBytes)throw new Error('Public response exceeds the size limit.');const reader=response.body.getReader();let count=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;count+=value.byteLength;if(count>maxBytes){await reader.cancel();throw new Error('Public response exceeds the size limit.');}chunks.push(value);}const bytes=new Uint8Array(count);let at=0;for(const chunk of chunks){bytes.set(chunk,at);at+=chunk.length;}if(!response.headers.get('content-type')?.includes('json'))throw new Error(response.ok?'The service returned an unreadable response.':`Public service returned HTTP ${response.status}.`);const data=JSON.parse(new TextDecoder().decode(bytes));if(!response.ok)throw new Error(String(data.message||data.error||`Public service returned HTTP ${response.status}.`).slice(0,500));return data;}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}
}

export async function search(query,base,signal,localSearch){
  if(signal?.aborted)throw new DOMException('Search stopped.','AbortError');
  const text=String(query).slice(0,500);let data;
  if(!String(base||'').trim()&&typeof localSearch==='function')data=await localSearch(text,{signal});
  else {const url=new URL(proxyBase(base)+'/search');url.searchParams.set('q',text);data=await readJSON(url,{signal});}
  if(signal?.aborted)throw new DOMException('Search stopped.','AbortError');
  const results=(Array.isArray(data.results)?data.results:[]).filter(x=>x&&safePublicURL(x.url)&&typeof x.snippet==='string').slice(0,4).map(x=>({title:String(x.title||'Public source').slice(0,180),url:safePublicURL(x.url),snippet:x.snippet.slice(0,750)}));if(!results.length)throw new Error('Search returned no usable evidence. Try another query or source.');return {results,timestamp:data.timestamp||new Date().toISOString(),provider:data.provider||'DuckDuckGo'};}
const bounded=x=>{if(!Number.isFinite(x)||Math.abs(x)>1e100)throw new Error('Use finite numbers no larger than 10^100.');return x;};
const fmt=x=>Number(bounded(x).toPrecision(12)).toString();
export function calculate(expression){
  if(expression.length>240)throw new Error('Please shorten the equation.');
  const tokens=expression.match(/(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?|sqrt|\*\*|[()+\-*/%]/gi)||[];
  if(tokens.join('').toLowerCase()!==expression.replace(/\s/g,'').toLowerCase()||tokens.length>64)throw new Error('Only numbers, arithmetic, parentheses and sqrt are supported.');
  let i=0,depth=0;
  function atom(){if(++depth>20)throw new Error('Equation is nested too deeply.');const token=tokens[i++];let value;if(token==='+'||token==='-')value=(token==='-'?-1:1)*power();else if(token==='('){value=sum();if(tokens[i++]!==')')throw new Error('Close each parenthesis.');}else if(token?.toLowerCase()==='sqrt'){if(tokens[i++]!=='(')throw new Error('Use sqrt(number).');value=Math.sqrt(sum());if(tokens[i++]!==')')throw new Error('Close each parenthesis.');}else if(token&&/^\d|^\./.test(token))value=Number(token);else throw new Error('Please check the equation.');depth--;return bounded(value);}
  function power(){let value=atom();if(tokens[i]==='**'){i++;const exponent=power();if(!Number.isInteger(exponent)||Math.abs(exponent)>100)throw new Error('Use whole-number exponents from -100 to 100.');if(value===0&&exponent<=0)throw new Error('Zero needs a positive exponent here.');value=bounded(value**exponent);}return value;}
  function product(){let value=power();while(['*','/','%'].includes(tokens[i])){const op=tokens[i++],right=power();if(right===0&&op!=='*')throw new Error('Division by zero is undefined.');value=bounded(op==='*'?value*right:op==='/'?value/right:((value%right)+right)%right);}return value;}
  function sum(){let value=product();while(['+','-'].includes(tokens[i])){const op=tokens[i++],right=product();value=bounded(op==='+'?value+right:value-right);}return value;}
  const value=sum();if(i!==tokens.length)throw new Error('Please check the equation.');return value;
}
const unit=name=>symbols[name.trim()]||aliases[name.trim().toLowerCase()];
export function quickAnswer(query){
  let text=query.trim().replace(/[?!.]+$/,'').replace(/^(?:please\s+)?(?:what(?:'s| is)|calculate|compute|evaluate|solve|convert)\s+/i,'');
  let conversion=text.match(/^([-+]?\d*\.?\d+(?:e[-+]?\d+)?)\s*(.+?)\s+(?:to|in|into|as|=)\s+(.+)$/i);
  const natural=text.match(/^how many (.+?) (?:are (?:there )?in|in|is)\s+(?:an? |one |([-+]?\d*\.?\d+)\s*)(.+)$/i);
  if(natural)conversion=[null,natural[2]||'1',natural[3],natural[1]];
  if(conversion){const [,n,from,to]=conversion,src=unit(from),dst=unit(to);if(src||dst){if(ambiguous.includes(from.toLowerCase())||ambiguous.includes(to.toLowerCase()))return {text:'Please specify the unit variant, such as US gallon, imperial gallon, or metric cup.',type:'clarification'};if(!src||!dst||src[0]!==dst[0])return {text:'Please choose supported units of the same kind.',type:'clarification'};let value=bounded(Number(n)),answer;if(src[0]==='temperature'){const k=src[1]==='°C'?value+273.15:src[1]==='°F'?(value-32)*5/9+273.15:value;if(k<0)return {text:'That temperature is below absolute zero.',type:'clarification'};answer=dst[1]==='°C'?k-273.15:dst[1]==='°F'?(k-273.15)*9/5+32:k;}else answer=value*Number(src[2])/Number(dst[2]);return {text:`${fmt(value)} ${src[1]} = ${fmt(answer)} ${dst[1]}.`,type:'calculation'};}}
  for(const [word,op]of [['multiplied by','*'],['divided by','/'],['to the power of','**'],['plus','+'],['minus','-'],['times','*']])text=text.replace(new RegExp(`\\b${word}\\b`,'gi'),op);
  text=text.replace(/[×x](?=\s*\d)/g,'*').replace(/÷/g,'/').replace(/−/g,'-').replace(/\^/g,'**').replace(/\s*(?:equals?|=)$/i,'');
  text=text.replace(/^(?:the )?square root of ([-+]?\d*\.?\d+)$/i,'sqrt($1)').replace(/^([-+]?\d*\.?\d+)\s*(?:%|percent) of ([-+]?\d*\.?\d+)$/i,'($1)/100*($2)');
  if(!/^[\d\s.eE+*/()%\-sqrt]+$/.test(text)||!/[+*/%\-]|sqrt/.test(text))return null;
  try{return {text:`${text} = ${fmt(calculate(text))}.`,type:'calculation'};}catch(error){return {text:error.message,type:'clarification'};}
}
export function weatherRequest(query,city=''){
  if(!/\b(weather|forecast|raining|temperature)\b/i.test(query)||/\b(why|define|definition|climate|yesterday|last|next|week|month|year|monday|tuesday|wednesday|thursday|friday|saturday|sunday|convert)\b|\d{4}-\d\d-\d\d/i.test(query)||/^what is (weather|temperature)\??$/i.test(query.trim()))return null;
  const mode=/\btomorrow\b/i.test(query)?'tomorrow':/\btoday\b/i.test(query)?'today':'current';const q=query.replace(/\b(right now|today|tomorrow|currently|now|please)\b/gi,'').replace(/[?!]+$/,'').trim();const match=q.match(/\b(?:in|for|at)\s+(.+)$/i)||q.match(/^(?:weather|forecast|temperature)\s+(.+)$/i);let place=match?.[1]?.trim()||city;if(/^(here|outside|my area|my location|like)$/i.test(place))place=city;return {city:place.slice(0,150),mode};
}
const weatherCodes={0:'clear sky',1:'mainly clear',2:'partly cloudy',3:'overcast',45:'fog',48:'rime fog',51:'light drizzle',53:'drizzle',55:'dense drizzle',61:'light rain',63:'rain',65:'heavy rain',71:'light snow',73:'snow',75:'heavy snow',80:'rain showers',81:'rain showers',82:'heavy showers',95:'thunderstorm',96:'thunderstorm with hail',99:'thunderstorm with hail'};
export async function weather(request,signal){
  if(!request.city)return {text:'Which city? Try “weather in Boston, Massachusetts, United States”, or save your city in Settings → Connection.',sources:[]};
  const parts=request.city.split(',').map(x=>x.trim()).filter(Boolean);const geo=new URL('https://geocoding-api.open-meteo.com/v1/search');geo.search=new URLSearchParams({name:parts[0],count:10,language:'en',format:'json'});const places=await readJSON(geo,{signal});let rows=(places.results||[]).filter(x=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude)&&Math.abs(x.latitude)<=90&&Math.abs(x.longitude)<=180);
  for(const p of parts.slice(1)){const aliases={us:'united states',usa:'united states',uk:'united kingdom'};const needle=aliases[p.toLowerCase()]||p.toLowerCase();rows=rows.filter(x=>['country','country_code','admin1','admin2','admin3'].some(k=>String(x[k]||'').toLowerCase()===needle));}
  const exact=rows.filter(x=>x.name?.toLowerCase()===parts[0].toLowerCase());if(exact.length)rows=exact;rows=[...new Map(rows.map(x=>[`${x.latitude},${x.longitude}`,x])).values()];const name=x=>[...new Set([x.name,x.admin1,x.country].filter(Boolean))].join(', ');
  if(rows.length!==1)return {text:rows.length?`Which place do you mean? ${rows.slice(0,3).map(name).join('; ')}. Include the region and country.`:`I couldn’t find ${request.city}. Please include the city, region and country.`,sources:[{title:'Open-Meteo locations',url:geo.href}]};
  const row=rows[0],url=new URL('https://api.open-meteo.com/v1/forecast');url.search=new URLSearchParams({latitude:row.latitude,longitude:row.longitude,current:'temperature_2m,apparent_temperature,weather_code,wind_speed_10m',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max',timezone:'auto',forecast_days:2});const data=await readJSON(url,{signal});const n=x=>{if(!Number.isFinite(x))throw new Error('Weather data is incomplete.');return Number(x.toFixed(1));};let text,condition;
  if(request.mode==='current'){const c=data.current;if(!c||typeof c.time!=='string')throw new Error('Current weather data is incomplete.');condition=c.weather_code;text=`${name(row)}: ${n(c.temperature_2m)}°C (${n(c.temperature_2m*9/5+32)}°F), ${weatherCodes[c.weather_code]||'conditions unavailable'}. Feels like ${n(c.apparent_temperature)}°C; wind ${n(c.wind_speed_10m)} km/h. Model estimate for ${c.time} (${data.timezone}).`;}
  else {const i=request.mode==='tomorrow'?1:0,d=data.daily;if(!d?.time?.[i])throw new Error('Forecast data is incomplete.');condition=d.weather_code[i];text=`${name(row)}, ${request.mode} (${d.time[i]}): ${weatherCodes[d.weather_code[i]]||'conditions unavailable'}, high ${n(d.temperature_2m_max[i])}°C, low ${n(d.temperature_2m_min[i])}°C. Chance of precipitation: ${n(d.precipitation_probability_max[i])}%. Forecasts can change.`;}
  return {text,orbitWeather:{code:condition,source:'open-meteo',label:name(row)+' · '+request.mode},sources:[{title:'Open-Meteo weather data',url:url.href},{title:'Weather methodology',url:'https://open-meteo.com/en/docs'}]};
}
