/** Browser speech and the optional paired voice clone stay on the user's devices. */
import {NeuralVoice} from './neural-voice.js';
import {normalizeVoice,sentenceChunks,NEURAL_VOICES,deliveryControls} from './voice-config.js';
export const PROFILES={Warm:{pitch:1,rate:.98},Bright:{pitch:1.12,rate:1.04},Calm:{pitch:.9,rate:.9},Storyteller:{pitch:1.04,rate:.94},Focused:{pitch:.95,rate:1.03},Playful:{pitch:1.18,rate:1.08}};
export function spokenText(text){return String(text).replace(/\n\s*Sources?:[\s\S]*$/i,'').replace(/```[\s\S]*?```/g,' Code is available in the message. ').replace(/\[([^\]]+)\]\(https?:\/\/[^)]+\)/g,'$1').replace(/https?:\/\/\S+/g,'').replace(/\[\d+\]/g,'').replace(/^#{1,6}\s*/gm,'').slice(0,1800);}
export class LocalVoice{
  constructor({onState=()=>{},onProgress=()=>{},onLevel=()=>{},helper=null,permission=async()=>{}}={}){this.onState=onState;this.recognition=null;this.utterance=null;this.generation=0;this.helper=helper;this.permission=permission;this.neural=new NeuralVoice({onState,onProgress,onLevel});this.cloning=false;}
  load(options){return this.neural.load(options);}
  unload(){this.stop();this.neural.unload();if(this.helper)this.helper('unload').catch(()=>{});}
  async preview(text,settings,{signal}={}){const config=normalizeVoice(settings.voice);return this.speak(text,{...config,language:({English:'en-US','Auto-detect':'en-US',Tagalog:'fil-PH',Spanish:'es-ES','Chinese (Mandarin)':'zh-CN',Japanese:'ja-JP',Italian:'it-IT',Russian:'ru-RU',Korean:'ko-KR'})[settings.language]||'en-US',profile:settings.voiceProfile,voiceURI:settings.voiceURI,rate:settings.rate,signal});}
  voices(){return globalThis.speechSynthesis?.getVoices().filter(v=>v.localService) || [];}
  async readyVoices(){if(this.voices().length)return this.voices();await new Promise(resolve=>{const timer=setTimeout(done,1500);const synth=globalThis.speechSynthesis;function done(){clearTimeout(timer);synth?.removeEventListener('voiceschanged',done);resolve();}synth?.addEventListener('voiceschanged',done,{once:true});});return this.voices();}
  stop(){this.generation++;this.neural.stop();if(this.cloning){this.cloning=false;this.helper?.('unload').catch(()=>{});}this.finishSpeech?.();this.finishSpeech=null;const recognition=this.recognition;this.recognition=null;try{recognition?.abort();}catch{}globalThis.speechSynthesis?.cancel();this.utterance=null;this.onState('idle');}
  async speak(text,{engine='system',neuralVoice='af_heart',cloneId='',pitch=0,depth=0,expression=.35,language='en-US',profile='Warm',voiceURI='',rate=1,emotion='neutral',signal}={}){
    if(signal?.aborted)throw new DOMException('Voice stopped.','AbortError');
    if(engine!=='system'){
      this.stop();const generation=this.generation;
      if(!language.startsWith('en'))throw new Error('These natural voices currently speak English. Select Installed system voice for this language in Voice Studio.');
      if(engine==='neural'){if(!this.neural.ready){await this.permission('internet');if(generation!==this.generation||signal?.aborted)return;}return this.neural.speak(spokenText(text),{neuralVoice,pitch,depth,expression,rate,emotion,signal});}
      if(engine!=='clone'||!this.helper||!cloneId)throw new Error('Choose a saved recording in Voice Studio and pair with the Mac companion.');
      this.cloning=true;const abort=()=>{if(generation===this.generation)this.stop();};signal?.addEventListener('abort',abort,{once:true});
      try{await this.neural.unlock();for(const chunk of sentenceChunks(spokenText(text),260)){if(signal?.aborted||generation!==this.generation)throw new DOMException('Voice stopped.','AbortError');this.onState('thinking');const audio=await this.helper('synthesize',{text:chunk,mode:'clone',voice:neuralVoice,language:NEURAL_VOICES.find(v=>v.id===neuralVoice)?.language||language,sample_id:cloneId,rate:Math.min(1.5,deliveryControls({rate,emotion,expression}).speed),pitch:deliveryControls({pitch,emotion,expression}).pitch,depth:depth/6},{signal});if(signal?.aborted||generation!==this.generation)throw new DOMException('Voice stopped.','AbortError');if(audio.mime!=='audio/wav'||typeof audio.base64!=='string'||audio.base64.length>12000000)throw new Error('The companion returned invalid voice audio.');const bytes=Uint8Array.from(atob(audio.base64),c=>c.charCodeAt(0)),buffer=await this.neural.context.decodeAudioData(bytes.buffer);if(signal?.aborted||generation!==this.generation)throw new DOMException('Voice stopped.','AbortError');await this.neural.play(buffer.getChannelData(0),buffer.sampleRate,{pitch:0,depth:0},{signal});}}finally{signal?.removeEventListener('abort',abort);if(generation===this.generation){this.cloning=false;this.onState('idle');}}return;
    }
    this.stop();this.finishSpeech?.();const generation=++this.generation;globalThis.speechSynthesis?.cancel();const voices=await this.readyVoices();if(signal?.aborted||generation!==this.generation)return;
    if(!voices.length)throw new Error('No installed local browser voice is available. Add a system voice or use the desktop edition.');
    const matching=voices.filter(v=>v.lang.toLowerCase().startsWith(language.split('-')[0].toLowerCase()));const index=Object.keys(PROFILES).indexOf(profile);const voice=voices.find(v=>v.voiceURI===voiceURI&&matching.includes(v))||matching[Math.max(0,index)%Math.max(1,matching.length)];
    if(!voice)throw new Error('No local voice is installed for this language. Choose an installed voice or language in Settings.');
    const delivery=PROFILES[profile]||PROFILES.Warm;const utterance=new SpeechSynthesisUtterance(spokenText(text));utterance.voice=voice;utterance.lang=voice.lang;utterance.rate=Math.max(.65,Math.min(1.5,rate*delivery.rate*(emotion==='excited'?1.05:emotion==='sad'?.94:1)));utterance.pitch=Math.max(.5,Math.min(1.8,delivery.pitch*2**(pitch/12)+(emotion==='happy'?.04:emotion==='sad'?-.06:0)));this.utterance=utterance;
    await new Promise((resolve,reject)=>{let finished=false;const abort=()=>{if(generation===this.generation)globalThis.speechSynthesis?.cancel();done();};function done(error){if(finished)return;finished=true;signal?.removeEventListener('abort',abort);error?reject(error):resolve();}this.finishSpeech=()=>done();signal?.addEventListener('abort',abort,{once:true});utterance.onstart=()=>{if(!finished&&generation===this.generation&&!signal?.aborted)this.onState('speaking');};utterance.onend=()=>done();utterance.onerror=event=>done(['canceled','interrupted'].includes(event.error)?null:new Error(`Voice playback failed: ${event.error}.`));if(signal?.aborted){abort();return;}try{globalThis.speechSynthesis.speak(utterance);}catch(error){done(error);}}).finally(()=>{if(generation===this.generation){this.utterance=null;this.finishSpeech=null;this.onState('idle');}});
  }
  recognitionClass(){return globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;}
  async speechAvailability(language='en-US'){const Recognition=this.recognitionClass();if(!Recognition||!('processLocally' in Recognition.prototype)||typeof Recognition.available!=='function')return 'unsupported';try{return await Recognition.available({langs:[language],processLocally:true});}catch{return 'unsupported';}}
  async installLanguage(language='en-US'){const Recognition=this.recognitionClass();if(!Recognition||typeof Recognition.install!=='function')throw new Error('This browser cannot install on-device dictation.');const ok=await Recognition.install({langs:[language],processLocally:true});if(!ok)throw new Error('The on-device language pack could not be installed.');return true;}
  async listen({language='en-US',onText=()=>{},onEnd=()=>{},onError=()=>{}}={}){
    this.stop();const generation=this.generation;const availability=await this.speechAvailability(language);if(generation!==this.generation)return;
    if(availability!=='available')throw new Error(availability==='downloadable'?'Install the on-device dictation language pack in Settings → Voice.':'On-device dictation is unavailable in this browser/language. Use typing or the complete desktop edition.');
    const Recognition=this.recognitionClass();const rec=new Recognition();rec.processLocally=true;rec.lang=language;rec.continuous=false;rec.interimResults=false;this.recognition=rec;
    rec.onstart=()=>{if(generation===this.generation)this.onState('listening');};rec.onresult=event=>{if(generation!==this.generation)return;const text=event.results?.[0]?.[0]?.transcript?.trim();if(text)onText(text);};rec.onerror=event=>{if(generation===this.generation&&event.error!=='aborted')onError(event.error==='no-speech'?'Sorry, can you say that again?':`Microphone: ${event.error}.`);};rec.onend=()=>{if(generation!==this.generation)return;this.recognition=null;this.onState('idle');onEnd();};try{rec.start();}catch(error){if(this.recognition===rec){this.recognition=null;this.onState('idle');}throw error;}
  }
}
