const assert=require('node:assert/strict'),fs=require('node:fs');
global.window=global;
require('../public/core.js');require('../public/timed.js');
const P=PMIX,T=PMIX_TIMED;
assert.deepEqual(['03:59:59','04:00','10:59:59','11:00','15:59:59','16:00','23:59:59'].map(P.dayPart),['UNASSIGNED','BK','BK','LN','LN','DN','DN']);
assert.equal(P.dayPart('4:00 PM'),'DN');assert.throws(()=>P.dayPart('24:00'));
assert.equal(P.basket(28,6,2),20);assert.equal(P.basket(28,null,2),null);assert.throws(()=>P.basket(5,4,2));
assert.equal(P.servingType('Meal- Platter w/Homefries'),'ML');assert.equal(P.servingType('Platter- Smothered w/Red Chile & Cheese'),'PL');assert.equal(P.servingType('No Potatoes'),null);
assert.equal(P.storeCode("Anita's New Mexico Style - Fairfax"),'FX');assert.equal(P.storeCode('Commissary'),null);assert.equal(P.channelCode('DIN'),'DI');assert.equal(P.qty('1,200'),1200);assert.equal(P.qty(''),null);assert.equal(P.qty('0'),0);assert.throws(()=>P.qty('12%'));
const compare=P.matrixFromRows([['Item','Fairfax','Fairfax','Chantilly','Chantilly'],['','Item Qty','% Qty (Group)','Item Qty','% Qty (Group)'],['Breakfast Burritos','28','100%','10','100%'],['BB Special','28','100%','10','100%']]);assert.deepEqual(compare.rows[1].values,{FX:28,CH:10});
const detail=P.hierarchyFromRows([['Menus','Qty sold'],['Total',28],['DINE IN',28],['Breakfast Burritos',28],['BB Special',28],['No Potatoes',2],['Platter- Smothered w/Red Chile & Cheese',6],['Meal- Platter w/Homefries',2]],'FX');P.attachForms(detail.rows,['FX'],true);assert.deepEqual(detail.rows.find(x=>x.item==='BB Special').forms.FX,{BK:20,PL:6,ML:2});
const batch=(channel,part,value,store='FX')=>({id:channel+part,label:'test',start:'2026-08-19',end:'2026-08-25',channel,part,confirmed:true,hhExclusive:true,stores:[store],rows:[{kind:'item',group:'Breakfast Burritos',item:'BB Special',values:{[store]:value},forms:{[store]:{BK:value-8,PL:6,ML:2}}}]});
const b=[batch('CO','BK',28),batch('DI','BK',38),batch('DD','DN',48)];P.validateBatch(b[0]);assert.throws(()=>P.validateBatch(batch('CO','ALL',100),b));
let r=P.report(b,{stores:['FX'],channels:['CO','DI'],parts:['BK']});assert.equal(r.rows[0].total,66);assert.equal(P.report(b,{stores:['FX'],channels:['DD'],parts:['DN']}).total,48);assert.equal(P.report(b,{stores:['FX','CH']}).rows[0].total,null);assert.throws(()=>P.report(b,{timeStart:'11:00'}));assert.throws(()=>P.report(b,{start:'2026-08-20'}));
r=P.formsReport(b,{stores:['FX'],channels:['CO']},['Breakfast Burritos\0BB Special']);assert.deepEqual(r.rows.map(x=>x.total),[20,6,2]);assert.equal(r.total,28);
const hh=batch('HH','BK',12);hh.hhExclusive=false;assert.throws(()=>P.report([b[1],hh],{stores:['FX']}));
assert.deepEqual(T.localParts('2026-08-19T15:00:00Z'),{date:'2026-08-19',time:'11:00:00'});
const raw=[['ID','Store','Group','Item','Quantity','Channel','Timestamp','Platter','Meal'],['x','FX','Breakfast Burritos','BB Special','28','DI','2026-08-19T11:00:00-04:00','6','2'],['y','FX','Breakfast Burritos','BB Special','1','CO','2026-08-19T16:00:00-04:00','0','0']];const timed=T.readTimed(raw);assert.equal(timed[0].part,'LN');let tb=T.timedBatches(timed,{start:'2026-08-19',end:'2026-08-19',timeStart:'11:00',timeEnd:'15:59'});assert.equal(tb.length,1);assert.equal(P.report(tb,{stores:['FX']}).total,28);assert.throws(()=>T.readTimed([...raw,raw[1]]));
console.log('Calculation checks passed: day parts, ET timestamps, multi-select filters, serving forms, missing data, duplicate/overlap rejection, and percent removal.');
