const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const sources=['core','timed','report-metadata','report-imports','dining','source-comparison','files','pdf-import','compare','template','io','report-document','report-csv'];
function context(extra={}){const c={console,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,DataView,Date,Blob,Response,DecompressionStream,crypto:require('node:crypto').webcrypto,Math,...extra};c.window=c;vm.createContext(c);for(const f of sources)vm.runInContext(fs.readFileSync('public/'+f+'.js','utf8'),c);return c;}
test('ProductMix filenames fill exact dates, invalid and conflicting periods remain unresolved, BK store headings do not mean breakfast',()=>{const c=context(),M=c.PMIX_METADATA;assert.equal(M.read('ProductMix_2026-08-19_2026-08-25.xlsx').start,'2026-08-19');assert.equal(M.read('ProductMix_2026-08-19_2026-08-25 (1).xlsx').end,'2026-08-25');assert.equal(M.read('PMIX - MAY 2025 - DN.xlsx').part,'DN');assert.equal(M.read('PMIX.pdf','AR AS BK CH FX HN LS MN SP VN').part,'ALL');assert.equal(M.read('ProductMix_2026-02-30_2026-03-01.csv').start,'');assert.equal(M.read('PMIX MAY 2025.xlsx','PMIX OCTOBER 2025').start,'');assert.match(M.read('PMIX MAY 2025.xlsx','PMIX OCTOBER 2025').warnings.join(),/conflict/);});
test('store-first filenames retain dates, canonical store order and distinct source periods',()=>{const c=context(),M=c.PMIX_METADATA,r={stores:['FX'],period:'2026-08-19 / 2026-08-25'};assert.equal(M.filename(r),'FX - PMIX Full 2026 - 0819_0825');assert.equal(M.filename({...r,stores:['FX','BK','AR']}),'AR-BK-FX - PMIX Full 2026 - 0819_0825');assert.equal(M.read(M.filename({...r,stores:['FX','BK','AR']})+'.xlsx').part,'ALL');assert.equal(M.read(M.filename(r)+'.xlsx').start,'2026-08-19');assert.equal(M.read(M.filename(r)+'.xlsx').end,'2026-08-25');assert.equal(M.filename({...r,period:'2025-12-30 / 2026-01-05'}),'FX - PMIX Full 2025-2026 - 1230_0105');assert.equal(M.read('FX - PMIX Full 2025-2026 - 1230_0105.xlsx').end,'2026-01-05');assert.equal(M.filename(r,{metric:'netSales'}),'FX - Net Sales 2026 - 0819_0825');assert.equal(M.title({stores:['FX'],view:'channels'}),'PMIX FULL · BY DINING OPTION · FX');const comparison={...r,comparison:true,sourceComparison:true,stores:['FX S1','FX S2','FX DIFF','FX VAR'],columns:[{store:'FX'},{store:'FX'},{},{}],batches:[{start:'2026-08-19',end:'2026-08-25'},{start:'2026-08-12',end:'2026-08-18'}]};assert.equal(M.filename(comparison),'FX - PMIX Full VS 2026 - 0812_0818 vs 0819_0825');});
test('independent revenue centers retain source money and do not invent item quantities',()=>{const c=context(),d=c.PMIX_FILES.parse([{name:'Revenue',rows:[['Location','Revenue center','Net sales'],['FX','Carry-Out','$100.50'],['CH','Carry-Out','$50.00'],['FX','Bar','-'],['CH','Bar','$20.00']]}],'NetSales_2026-08-19_2026-08-25.csv').docs[0],bs=c.PMIX_FILES.batches(d);let added=[];for(const b of bs){c.PMIX.validateBatch(b,added);added.push(b);}const r=c.PMIX.report(bs,{stores:['CH','FX'],metric:'netSales'});assert.equal(r.total,170.5);assert.equal(c.PMIX.report(bs,{stores:['CH','FX']}).total,null);assert.equal(bs[1].channel,'BAR');});
test('formatted workbook tabs preserve scope and exclude ORIG, subtotals and cells outside the print area',()=>{const c=context(),rows=[['Item','AR','FX'],[{text:'Beverages',bold:true},5,8],[{text:'Coffee',bold:false},5,8],['Duplicate hidden below print area',99,99]],sheet=channel=>({name:channel,header:'MAY 2025',printArea:"'"+channel+"'!$A$1:$C$3",rows});const bundle=c.PMIX_FILES.parse([sheet('CO'),sheet('DD'),sheet('ORIG')],'PMIX MAY 2025 - LN.xlsx');assert.equal(bundle.docs.length,2);for(const doc of bundle.docs){const b=c.PMIX_FILES.batches(doc)[0];assert.equal(b.part,'LN');assert.equal(b.rows.filter(r=>r.kind==='item').length,1);assert.equal(b.rows.find(r=>r.kind==='item').values.FX,8);}});
test('CSV exports numeric variance, grand totals, quoting and spreadsheet-injection protection',()=>{const c=context(),csv=c.PMIX_CSV.csv({stores:['FX'],rows:[{group:'Drinks',item:'=HYPERLINK("bad")',values:[-4],total:-4,format:'currency'}],totals:[-4],total:-4},{title:'Report',subtitle:'Dates'});assert.match(csv,/"'=HYPERLINK\(""bad""\)"/);assert.match(csv,/,-4\r\n/);assert.doesNotMatch(csv.split("\r\n")[0],/"TOTAL"/);assert.match(csv,/Grand total/);assert.ok(csv.startsWith('\uFEFF'));});
test('Excel comparison formulas use Previous minus Current and grand-total denominators, including cached results',async()=>{const c=context(),B=(id,start,v)=>({id,label:id,start,end:start,part:'ALL',channel:'CO',confirmed:true,stores:['FX','CH'],zeroForMissing:true,rows:[{kind:'item',group:'BB',item:'BB Special',values:v}]}),r=c.PMIX_COMPARE.compare(c.PMIX.report([B('a','2026-08-01',{FX:100,CH:0})],{stores:['CH','FX']}),c.PMIX.report([B('b','2026-08-08',{FX:60,CH:5})],{stores:['CH','FX']}));const z=await c.PMIX_IO.unzip(c.PMIX_IO.makeXlsx(r,{title:'Compare',subtitle:'Dates',note:'',prepared:'09/12/26',filename:'Test',footerPath:'Downloads'})),xml=new TextDecoder().decode(z['xl/worksheets/sheet1.xml']);assert.match(xml,/<f>IF\(COUNT\(B3,B4\)=2,B3-B4/);assert.match(xml,/\(D7-D8\)\/D7/);assert.match(xml,/Times New Roman/);assert.match(xml,/&amp;Z\n&amp;F/);assert.match(xml,/n.a./);});
// Small DOM model with the standard return value of Element.append (undefined).
// This exercises controller events and saved state without a browser or hosted preview.
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.listeners={};this.attrs={};this._value='';this.type='';this.checked=false;this.disabled=false;this.textContent='';this.dataset={};this.classList={add(){},remove(){},toggle(){}};}
 append(...nodes){this.children.push(...nodes);for(const n of nodes)if(n instanceof Element)n.parent=this;}
 appendChild(n){this.append(n);return n;}
 replaceChildren(...nodes){this.children=[];this._value='';this.append(...nodes);}
 set value(v){this._value=String(v);}
 get value(){return this.tagName==='SELECT'?(this._value||this.children[0]?.value||''):this._value;}
 get selectedOptions(){return this.children.filter(c=>c.value===this.value);}
 setAttribute(k,v){this.attrs[k]=String(v);}
 addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);}
 dispatchEvent(e){for(const fn of this.listeners[e.type]||[])fn(e);}
 querySelector(){return null;}
 scrollIntoView(){} focus(){} click(){return this.onclick?.({});}
}
function controller(){const html=fs.readFileSync('public/index.html','utf8'),ids=new Map();for(const m of html.matchAll(/<([a-z]+)\b([^>]*\bid="([^"]+)"[^>]*)>/g)){const e=new Element(m[1]);e.id=m[3];e.type=m[2].match(/\btype="([^"]+)"/)?.[1]||'';e.value=m[2].match(/\bvalue="([^"]*)"/)?.[1]||'';e.checked=/\bchecked\b/.test(m[2]);ids.set(e.id,e);if(e.tagName==='SELECT'){const tail=html.slice(m.index+m[0].length).split('</select>')[0];for(const option of tail.matchAll(/<option(?: value="([^"]*)")?[^>]*>([^<]*)<\/option>/g)){const o=new Element('option');o.value=option[1]??option[2];o.textContent=option[2];e.append(o);}}}const events=[];const document={getElementById:id=>ids.get(id),createElement:t=>new Element(t),createTextNode:t=>t,dispatchEvent:e=>events.push(e.type)},saved=new Map(),downloads=[];const c=context({document,CustomEvent:class{constructor(type){this.type=type;}},localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)}});c.PMIX_IO.download=(...a)=>downloads.push(a);vm.runInContext(fs.readFileSync('public/app.js','utf8'),c);return {c,ids,events,saved,downloads};}
test('upload autofills form, render survives DOM append, filter changes invalidate preview and Save includes settings',async()=>{const {c,ids,events,downloads}=controller(),data='Location,Item,Quantity,Net sales\nFX,Coffee,10,25.50\n',file={name:'ProductMix_2026-08-19_2026-08-25.csv',size:data.length,text:async()=>data,arrayBuffer:async()=>new TextEncoder().encode(data).buffer};await c.PMIX_STUDIO.readFiles([file]);await ids.get('importFiles').onclick();assert.equal(ids.get('filterStart').value,'2026-08-19');assert.equal(ids.get('filterEnd').value,'2026-08-25');assert.equal(c.PMIX_CURRENT().report.total,10);assert.ok(events.includes('pmix:report-updated'));ids.get('reportMetric').value='netSales';ids.get('reportMetric').dispatchEvent({type:'change'});assert.equal(c.PMIX_CURRENT().report.total,25.5);ids.get('reportLayout').value='compact';ids.get('footerPath').value='Downloads';await ids.get('saveProject').onclick();const saved=JSON.parse(downloads.at(-1)[0]);assert.equal(saved.version,2);assert.equal(saved.settings.fields.reportMetric,'netSales');assert.equal(saved.settings.fields.reportLayout,'compact');ids.get('filterStart').value='2026-08-20';ids.get('filterStart').dispatchEvent({type:'change'});assert.equal(c.PMIX_CURRENT().report,null);assert.equal(ids.get('previewReport').disabled,true);assert.equal(ids.get('exportCsv').disabled,true);});
test('two source files auto-select VS, reverse updates signs, and three files keep periods separate',async()=>{const {c,ids}=controller();const file=(store,start,end,qty)=>{const data='Location,Item,Quantity\n'+store+',Coffee,'+qty+'\n';return {name:'ProductMix_'+start+'_'+end+'.csv',size:data.length,text:async()=>data,arrayBuffer:async()=>new TextEncoder().encode(data).buffer};};await c.PMIX_STUDIO.readFiles([file('FX','2026-08-01','2026-08-07',100),file('CH','2026-08-08','2026-08-14',60)]);await ids.get('importFiles').onclick();assert.equal(ids.get('sourceLayout').value,'versus');let r=c.PMIX_CURRENT().report;assert.ok(r);assert.deepEqual(Array.from(r.rows[0].values.slice(0,4)),[100,60,40,.4]);assert.equal(r.omitTotal,true);assert.equal(c.PMIX_CURRENT().meta.subtitle.includes('All Dining Options'),true);ids.get('reverseSources').checked=true;ids.get('reverseSources').dispatchEvent({type:'change'});r=c.PMIX_CURRENT().report;assert.deepEqual(Array.from(r.rows[0].values.slice(0,4)),[60,100,-40,-40/60]);await c.PMIX_STUDIO.readFiles([file('FX','2026-08-15','2026-08-21',40)]);await ids.get('importFiles').onclick();assert.equal(ids.get('sourceLayout').value,'sources');r=c.PMIX_CURRENT().report;assert.equal(r.stores.length,6);assert.equal(r.total,null);assert.equal(r.sourceLegend.length,3);});
test('VS grand totals use weighted variance and Excel formulas remain editable',async()=>{const c=context(),P=c.PMIX;const batch=(id,date,values)=>({id,fileHash:id,sourceFormat:'same',label:id,sourceFile:id,start:date,end:date,stores:['FX'],channel:'CO',part:'ALL',confirmed:true,zeroForMissing:true,rows:values.map((v,i)=>({kind:'item',group:'BB',item:'Item '+i,values:{FX:v}}))});const a=batch('a','2026-08-01',[100,20,0]),b=batch('b','2026-08-08',[60,30,5]),r=c.PMIX_SOURCES.report([[a],[b]],(bs,f)=>P.report(bs,f),{stores:['FX'],combineNames:true},'versus',false);assert.deepEqual(Array.from(r.totals.slice(0,4)),[120,95,25,25/120]);assert.equal(r.rows[2].values[3],null);const z=await c.PMIX_IO.unzip(c.PMIX_IO.makeXlsx(r,{title:'BB PMIX VS',subtitle:'Dates',prepared:'09/12/26',layout:'compact'})),xml=new TextDecoder().decode(z['xl/worksheets/sheet1.xml']);assert.match(xml,/\(B6-C6\)\/B6/);assert.match(xml,/<oddHeader>[^<]*BB PMIX VS/);assert.doesNotMatch(xml,/<t[^>]*>BB PMIX VS<\/t>/);assert.match(xml,/ht="12.5"/);});
test('available dining choices are hierarchical and explicit subtypes preserve quantities',()=>{const c=context(),D=c.PMIX_DINING;const doc=c.PMIX_FILES.parse([{name:'Export',rows:[['Location','Item','Quantity','Dining option'],['FX','Coffee','10','W/I'],['FX','Coffee','4','CT-P/U'],['FX','Coffee','2','DI']]}],'ProductMix_2026-08-19_2026-08-25.csv');const bs=doc.docs.flatMap(d=>c.PMIX_FILES.batches(d)),choices=D.choices(bs).map(v=>v[0]);assert.deepEqual(Array.from(bs.map(b=>b.channel)),['WI','CTPU','IN']);assert.ok(choices.includes('@CO'));assert.ok(!choices.includes('PATIO'));assert.equal(D.subtitle([],bs),'All Dining Options');const f={stores:['FX'],channels:D.expand(['@CO'])};assert.equal(c.PMIX.report(bs,f).total,10);assert.equal(D.subtitle(['@CO'],bs),'W/I');});
test('modifier quantities retain actual occurrences and do not count parent totals',()=>{const c=context();const doc=c.PMIX_FILES.parse([{name:'All levels',rows:[['Type','Menu','Menu group','Item','Modifiers, special requests','Qty sold'],['menuItem','DINE IN','BB','BB Special','',28],['modifier','DINE IN','BB','BB Special','Platter',6],['modifier','DINE IN','BB','BB Special','Meal',2],['modifier','DINE IN','BB','BB Special','No Potatoes',4]]}],'ProductMix_2026-08-19_2026-08-25.xlsx');doc.store='FX';const bs=c.PMIX_FILES.batches(doc),r=c.PMIX_DINING.modifiers(bs,{stores:['FX']},['No Potatoes']);assert.equal(r.total,4);assert.equal(r.rows.length,1);assert.equal(c.PMIX.report(bs,{stores:['FX']}).total,28);assert.ok(r.modifierCounts);});
