import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync}from 'node:sqlite';import fs from 'node:fs';import worker from '../src/worker.mjs';
const db=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+file,'utf8'));const wrap=q=>({bind(...args){const stmt=db.prepare(q);return {first:async()=>stmt.get(...args)||null,all:async()=>({results:stmt.all(...args)}),run:async()=>stmt.run(...args)}}});
const sha=async s=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex');
const env={DB:{prepare:wrap,batch:async q=>{db.exec('BEGIN');try{const r=await Promise.all(q.map(p=>p.run()));db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}},OWNER_EMAIL:'owner@example.test',PIN_SALT:'fixture',PIN_HASH:await sha('fixture1234'),SESSION_SECRET:'test-session-secret'};
const call=(path,method='GET',data,cookie='',email='owner@example.test')=>worker.fetch(new Request('https://pmix.test/api/'+path,{method,headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':email,origin:'https://pmix.test',cookie},body:data===undefined?undefined:JSON.stringify(data)}),env);
let cookie;
test('owner only, server PIN, signed cookie and cross-origin denial',async()=>{assert.equal((await call('status','GET',undefined,'','someone@example.test')).status,403);assert.equal((await call('layouts')).status,401);assert.equal((await call('unlock','POST',{pin:'9999'})).status,401);const r=await call('unlock','POST',{pin:'1234'});assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);assert.equal((await call('layouts','GET',undefined,cookie)).status,200);assert.equal((await call('layouts','GET',undefined,cookie+'fake')).status,401);});
test('durable profile revision changes once, rejects malicious fields and owner access stays enforced',async()=>{const p={key:'a'.repeat(64),name:'Toast fixture',mappings:{'Menu':'CO'},columns:null};assert.equal((await call('layouts','POST',p,cookie)).status,200);await call('layouts','POST',p,cookie);const status=await(await call('status','GET',undefined,cookie)).json();assert.equal(status.memoryRevision,1);const all=await(await call('layouts','GET',undefined,cookie)).json();assert.equal(all.profiles[0].key,p.key);assert.equal((await call('layouts','POST',{...p,columns:{execute:3}},cookie)).status,400);assert.equal((await call('help','POST',{question:'Help'},cookie)).status,503);});

test('chat persistence, retry deduplication, search pagination and owner privacy',async()=>{const c={requestId:'fixture-conversation-001',question:'Remember Fairfax operations',answer:'Reviewed the staffing notes.',sources:[{title:'Source',url:'https://example.com',snippet:'Reference'}]};assert.equal((await call('chats','POST',c)).status,401);assert.equal((await call('chats','POST',c,cookie)).status,200);await call('chats','POST',c,cookie);let r=await(await call('chats?q=Fairfax','GET',undefined,cookie)).json();assert.equal(r.chats.length,1);assert.equal(r.chats[0].sources[0].url,c.sources[0].url);assert.equal((await call('chats','GET',undefined,cookie,'other@example.test')).status,403);assert.equal((await(await call('chats?q=%25','GET',undefined,cookie)).json()).chats.length,0);assert.equal((await call('chats','POST',{...c,requestId:'malicious-source-001',sources:[{url:'javascript:alert(1)'}]},cookie)).status,400);for(let i=0;i<26;i++)await call('chats','POST',{...c,requestId:'fixture-pagination-'+i},cookie);r=await(await call('chats','GET',undefined,cookie)).json();assert.equal(r.chats.length,25);assert.ok(r.next);const second=await(await call('chats?before='+r.next,'GET',undefined,cookie)).json();assert.equal(second.chats.length,2);assert.equal(second.next,null);assert.equal((await(await call('chats?mode=context&q=What%20about%20Fairfax','GET',undefined,cookie)).json()).chats.length,25);const id=r.chats[0].id;await call('chats','DELETE',{id},cookie);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM chat_history WHERE id=?').get(id).n,0);const evil=new Request('https://pmix.test/api/chats',{method:'POST',headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.test',origin:'https://evil.test',cookie},body:JSON.stringify(c)});assert.equal((await worker.fetch(evil,env)).status,403);});

test('creation settings require owner and PIN, encrypt keys, and never return secrets',async()=>{assert.equal((await call('create/status')).status,401);assert.equal((await call('create/status','GET',undefined,cookie,'other@example.test')).status,403);let r=await(await call('create/status','GET',undefined,cookie)).json();assert.equal(r.image,false);assert.equal((await call('create/image','POST',{prompt:'An image',size:'1024x1024'},cookie)).status,503);const original=globalThis.fetch;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/models');return new Response(JSON.stringify({data:[]}));};try{const key='sk-test-ONLY-fixture-value-123456789';r=await(await call('create/connection','POST',{provider:'openai',key},cookie)).json();assert.equal(r.saved,true);const stored=db.prepare('SELECT value FROM max_settings').get().value;assert.ok(!stored.includes(key));r=await(await call('create/status','GET',undefined,cookie)).json();assert.equal(r.image,true);assert.ok(!JSON.stringify(r).includes(key));await call('create/connection','DELETE',{provider:'openai'},cookie);assert.equal((await(await call('create/status','GET',undefined,cookie)).json()).image,false);}finally{globalThis.fetch=original;}});
test('creation drafts sync and delete within owner scope; forged video links fail',async()=>{const d={id:'draft-fixture-123456',title:'Private draft',kind:'document',content:'Example body'};assert.equal((await call('create/drafts','POST',d,cookie)).status,200);assert.equal((await(await call('create/drafts','GET',undefined,cookie)).json()).drafts.length,1);assert.equal((await(await call('create/draft?id='+d.id,'GET',undefined,cookie)).json()).content,d.content);assert.equal((await call('create/draft?id='+d.id,'GET',undefined,cookie,'other@example.test')).status,403);assert.equal((await call('create/video-status','POST',{ticket:'forged.signature'},cookie)).status,403);await call('create/drafts','DELETE',{id:d.id},cookie);assert.equal((await call('create/draft?id='+d.id,'GET',undefined,cookie)).status,404);});
